export const MAIN_COLOR = '#434a54'
export const SELECTION_BACKGROUND = '#f1ece4'
export const SELECTION_COLOR = '#434a54'
export const BOX_SHADOW_COLOR = '#ccc'
export const RELATED_ARTICLES_BACKGROUND_COLOR = '#f9f9f9'
export const RELATED_ARTICLES_AUTHOR_TEXT_COLOR = '#878787'
export const QUOTE_AUTHOR_TEXT_COLOR = '#949494'
export const QUOTE_AUTHOR_POSITION_TEXT_COLOR = '#c6c6c6'
export const TWEETABLE_QUOTE_HOVER_COLOR = '#5498ff'
export const BACKGROUND_COLOR_SECONDARY = '#f9f9f9'
export const TEXT_COLOR_PRIMARY = '#ffffff'
export const TEXT_COLOR_SECONDARY = '#000000'
export const LAYOUT_DYNAMIC = 'dynamic'
export const CONTAINER_WIDTH = 1200 // 1200 - (24 * 2)
export const GRID_UNIT = 8
export const ARTICLE_SECTION_HORIZONTAL_PADDING = 3 * GRID_UNIT
export const ARTICLE_SECTION_VERTICAL_PADDING = 2 * GRID_UNIT
export const ARTICLE_COLUMN_WIDTH = 640
export const PULL_QUOTE_MAX_WIDTH =
  1000 + 2 * ARTICLE_SECTION_HORIZONTAL_PADDING
export const ARTICLE_SECTION_WIDTH =
  ARTICLE_COLUMN_WIDTH + 2 * ARTICLE_SECTION_HORIZONTAL_PADDING
export const ARTICLE_LIST_WIDTH = 136 * GRID_UNIT
export const ARTICLE_LIST_HORIZONTAL_PADDING = 3 * GRID_UNIT
export const ARTICLE_LIST_PADDING_TOP = 30 * GRID_UNIT
export const ARTICLE_LIST_PADDING_BOTTOM = 22 * GRID_UNIT
export const HIGHLIGHTS_PAGE_SECTION_HORIZONTAL_PADDING = 4 * GRID_UNIT
export const HIGHLIGHTS_PAGE_SECTION_VERTICAL_PADDING = 8 * GRID_UNIT
export const HIGHLIGHTS_PAGE_SECTION_MAX_WIDTH =
  1024 + 2 * HIGHLIGHTS_PAGE_SECTION_HORIZONTAL_PADDING
export const BREAKPOINTS = {
  base: CONTAINER_WIDTH,
  xl: 1440,
  lg: 1024,
  md: 768,
  sm: 480,
}
